# Generated by Django 4.0.6 on 2022-09-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='Airline_Companies',
            new_name='Airline',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
