# Generated by Django 4.0.6 on 2022-09-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_country_departing_flights_and_more'),
        ('accounts', '0003_alter_airline_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='flights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='flights.flight'),
        ),
    ]
