# Generated by Django 4.0.6 on 2022-09-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_airline_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='flights',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='flights',
        ),
    ]
