# Generated by Django 4.0.6 on 2022-09-21 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='phone number'),
        ),
    ]
