# Generated by Django 4.0.6 on 2022-09-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_alter_flight_passengers'),
        ('accounts', '0007_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='airlines', to='flights.country'),
            preserve_default=False,
        ),
    ]
