# Generated by Django 4.0.6 on 2022-09-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_alter_flight_passengers'),
        ('accounts', '0009_alter_customer_first_name_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='airlines', to='flights.country'),
        ),
    ]
