# Generated by Django 4.0.6 on 2022-11-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_country_name_alter_country_pic'),
        ('accounts', '0010_alter_administrator_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='airlines', to='flights.country'),
            preserve_default=False,
        ),
    ]
