# Generated by Django 4.0.6 on 2022-09-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('landing_time', models.DateTimeField(auto_now=True)),
                ('tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departing_flights', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin_country', to='flights.flights')),
                ('landing_flights', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_country', to='flights.flights')),
            ],
        ),
    ]
