# Generated by Django 4.0.6 on 2022-09-20 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_flights_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
