# Generated by Django 4.0.6 on 2022-09-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_departure_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='departing_flights',
        ),
        migrations.RemoveField(
            model_name='country',
            name='landing_flights',
        ),
        migrations.AddField(
            model_name='country',
            name='pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_country',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='landing_flights', to='flights.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_country',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departing_flights', to='flights.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='tickets',
            field=models.IntegerField(default=150),
        ),
    ]
