# Generated by Django 4.0.6 on 2022-09-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_country_departing_flights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='landing_flights', to='flights.country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departing_flights', to='flights.country'),
        ),
    ]
