# Generated by Django 4.0.6 on 2022-09-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_airline_flights_remove_customer_flights'),
        ('flights', '0005_alter_flight_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='accounts.airline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(related_name='flights', to='accounts.customer'),
        ),
    ]
