# Generated by Django 4.0.6 on 2022-09-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_airline_flights_remove_customer_flights'),
        ('flights', '0006_flight_airline_flight_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='accounts.airline'),
        ),
    ]
