# Generated by Django 4.0.6 on 2022-09-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_airline_flights_remove_customer_flights'),
        ('flights', '0009_alter_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(null=True, related_name='flights', to='accounts.customer'),
        ),
    ]
