# Generated by Django 4.0.6 on 2022-09-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_administrator_first_name_and_more'),
        ('flights', '0011_alter_flight_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='flights', to='accounts.customer'),
        ),
    ]
