# Generated by Django 4.0.6 on 2022-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_alter_flight_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
