# Generated by Django 4.0.6 on 2022-11-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_alter_flight_options_alter_country_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='pic',
            field=models.URLField(default='https://www.supercoloring.com/sites/default/files/styles/coloring_medium/public/cif/2022/03/question-mark-flag-emoji-coloring-page.png'),
        ),
    ]
